import type { Metadata } from "next";
import { Outfit, Ovo } from "next/font/google";
import "./globals.css";

const OutFit = Outfit({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500"],
});

const OvO = Ovo({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href="/letter-t.png" />
      </head>

      <body className={`${OutFit.className} ${OvO.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
